### ISSUE TITLE
Bug in s_at function in misc.cpp

### ISSUE THREAD

**Issue by kevinhendricks** [csstidy-c/csstidy#3]
The s_at function in misc.cpp has a bug that actually prevents it from working properly:

```
// Save replacement for .at()
char s_at(const string &istring, const int pos)
{
	if(pos > (istring.length()-1) && pos < 0)
	{
		return 0;
	}
	else
	{
		return istring[pos];
	}
}
```

The bug is in this line:

	if(pos > (istring.length()-1) && pos < 0)

which will never be true as pos can not both at the same time.

You need to change the && into || for this function to actually act like a protective at function.

**Comment by csstidy-c** [comment]
fixed with 299e9c35132c4c152c5425443a1157a6598addd2
thank you!
